# Generated by Django 5.0.7 on 2024-08-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('bitmask', models.JSONField()),
            ],
        ),
    ]
